remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Oh Py God's Blog
author: Vibhav D
description: Product Security, Automation, and much more

# variables
github:
  repository_url: https://github.com/Oh-Py-God/oh-py-god.github.io
  owner_url: https://github.com/Oh-Py-God
